# Sistema de recomendacion

In [1]:
import numpy as np

## Algoritmo

In [2]:
def SisRec(V_inc, k, max_iter, omega):
    (m, n) = V_inc.shape
    
    Z = np.copy(V_inc)
    Z[omega] = 0.0
    W = np.random.uniform(0.0, 1.0, size=(m,k))
    H = np.random.uniform(0.0, 1.0, size=(n,k))
    
    
    for t in range(max_iter):
        H = (Z.T @ W) @ (np.linalg.pinv( W.T @ W))
        H = np.clip(H, 0.0, np.inf)
        
        W = (Z @ H) @ (np.linalg.pinv( H.T @ H))
        W = np.clip(W, 0.0, np.inf)
        
        Z[omega] = (W@H.T)[omega]

    return (W, H) 

## Cargar datos

In [3]:
V_original = np.loadtxt('V_complete.txt')

In [4]:
V_original

array([[30., 12., 24.,  8., 12., 14., 12., 12., 22., 24., 14., 10., 14.,
        24., 20., 12.],
       [30., 21., 15., 11., 21., 26., 12., 21., 10., 15., 17., 16.,  8.,
        15., 23., 12.],
       [15.,  9.,  9.,  5.,  9., 11.,  6.,  9.,  7.,  9.,  8.,  7.,  5.,
         9., 11.,  6.],
       [35., 16., 26., 10., 16., 19., 14., 16., 23., 26., 17., 13., 15.,
        26., 24., 14.],
       [15.,  9.,  9.,  5.,  9., 11.,  6.,  9.,  7.,  9.,  8.,  7.,  5.,
         9., 11.,  6.],
       [25., 11., 19.,  7., 11., 13., 10., 11., 17., 19., 12.,  9., 11.,
        19., 17., 10.],
       [45., 24., 30., 14., 24., 29., 18., 24., 25., 30., 23., 19., 17.,
        30., 32., 18.],
       [30., 15., 21.,  9., 15., 18., 12., 15., 18., 21., 15., 12., 12.,
        21., 21., 12.],
       [25., 11., 19.,  7., 11., 13., 10., 11., 17., 19., 12.,  9., 11.,
        19., 17., 10.],
       [20., 13., 11.,  7., 13., 16.,  8., 13.,  8., 11., 11., 10.,  6.,
        11., 15.,  8.],
       [45., 24., 30., 14., 24

In [5]:
V_incomplete = np.loadtxt('V_incomplete.txt')

In [6]:
V_incomplete

array([[30., nan, 24.,  8., 12., 14., 12., nan, 22., nan, nan, 10., 14.,
        24., 20., nan],
       [30., 21., nan, 11., 21., nan, 12., 21., nan, 15., 17., nan,  8.,
        15., 23., nan],
       [nan,  9., nan, nan,  9., nan, nan, nan,  7.,  9.,  8.,  7.,  5.,
        nan, 11.,  6.],
       [35., nan, nan, 10., nan, nan, nan, nan, 23., nan, 17., 13., 15.,
        26., 24., nan],
       [nan,  9.,  9.,  5., nan, nan, nan, nan, nan,  9.,  8., nan, nan,
         9., 11., nan],
       [nan, 11., 19.,  7., nan, 13., 10., 11., 17., 19., 12.,  9., 11.,
        19., 17., nan],
       [45., 24., 30., nan, nan, 29., 18., nan, 25., 30., nan, 19., 17.,
        30., 32., nan],
       [nan, nan, 21., nan, 15., 18., 12., 15., 18., 21., 15., 12., 12.,
        21., 21., 12.],
       [25., 11., nan,  7., 11., 13., 10., 11., 17., 19., 12.,  9., nan,
        19., nan, nan],
       [nan, 13., 11.,  7., 13., 16.,  8., nan,  8., 11., 11., nan, nan,
        11., 15.,  8.],
       [45., 24., 30., 14., 24

## Conjunto de entradas no definidas

In [7]:
omega = np.isnan(V_incomplete)

## Estimar entradas no definidas

In [8]:
(W_hat, H_hat) = SisRec(V_incomplete, 2, 1000, omega )

## Verificar resultados

In [9]:
V_hat = W_hat@H_hat.T

In [10]:
V_hat

array([[30., 12., 24.,  8., 12., 14., 12., 12., 22., 24., 14., 10., 14.,
        24., 20., 12.],
       [30., 21., 15., 11., 21., 26., 12., 21., 10., 15., 17., 16.,  8.,
        15., 23., 12.],
       [15.,  9.,  9.,  5.,  9., 11.,  6.,  9.,  7.,  9.,  8.,  7.,  5.,
         9., 11.,  6.],
       [35., 16., 26., 10., 16., 19., 14., 16., 23., 26., 17., 13., 15.,
        26., 24., 14.],
       [15.,  9.,  9.,  5.,  9., 11.,  6.,  9.,  7.,  9.,  8.,  7.,  5.,
         9., 11.,  6.],
       [25., 11., 19.,  7., 11., 13., 10., 11., 17., 19., 12.,  9., 11.,
        19., 17., 10.],
       [45., 24., 30., 14., 24., 29., 18., 24., 25., 30., 23., 19., 17.,
        30., 32., 18.],
       [30., 15., 21.,  9., 15., 18., 12., 15., 18., 21., 15., 12., 12.,
        21., 21., 12.],
       [25., 11., 19.,  7., 11., 13., 10., 11., 17., 19., 12.,  9., 11.,
        19., 17., 10.],
       [20., 13., 11.,  7., 13., 16.,  8., 13.,  8., 11., 11., 10.,  6.,
        11., 15.,  8.],
       [45., 24., 30., 14., 24

## Verificar error de reconstruccion

In [11]:
np.linalg.norm(V_original - V_hat)

2.5068196698368835e-13