In [7]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures
X = np.arange(24).reshape(8, 3)
X

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [8]:
poly = PolynomialFeatures(2)
poly.fit_transform(X)

array([[  1.,   0.,   1.,   2.,   0.,   0.,   0.,   1.,   2.,   4.],
       [  1.,   3.,   4.,   5.,   9.,  12.,  15.,  16.,  20.,  25.],
       [  1.,   6.,   7.,   8.,  36.,  42.,  48.,  49.,  56.,  64.],
       [  1.,   9.,  10.,  11.,  81.,  90.,  99., 100., 110., 121.],
       [  1.,  12.,  13.,  14., 144., 156., 168., 169., 182., 196.],
       [  1.,  15.,  16.,  17., 225., 240., 255., 256., 272., 289.],
       [  1.,  18.,  19.,  20., 324., 342., 360., 361., 380., 400.],
       [  1.,  21.,  22.,  23., 441., 462., 483., 484., 506., 529.]])

In [9]:
poly = PolynomialFeatures(interaction_only=True)
poly.fit_transform(X)

array([[  1.,   0.,   1.,   2.,   0.,   0.,   2.],
       [  1.,   3.,   4.,   5.,  12.,  15.,  20.],
       [  1.,   6.,   7.,   8.,  42.,  48.,  56.],
       [  1.,   9.,  10.,  11.,  90.,  99., 110.],
       [  1.,  12.,  13.,  14., 156., 168., 182.],
       [  1.,  15.,  16.,  17., 240., 255., 272.],
       [  1.,  18.,  19.,  20., 342., 360., 380.],
       [  1.,  21.,  22.,  23., 462., 483., 506.]])