In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
tf.__version__

'2.6.0'

# Tensors

In [ ]:
a = tf.constant( 2.0, shape=[4], dtype= tf.float32 )

In [ ]:
print(a)

tf.Tensor([2. 2. 2. 2.], shape=(4,), dtype=float32)


In [ ]:
b = tf.constant( 3.0, shape=[4])

In [ ]:
print(b)

tf.Tensor([3. 3. 3. 3.], shape=(4,), dtype=float32)


In [ ]:
c = tf.add(a, b)

In [ ]:
print(c)

tf.Tensor([5. 5. 5. 5.], shape=(4,), dtype=float32)


In [ ]:
a + b

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([5., 5., 5., 5.], dtype=float32)>

In [ ]:
a*b 

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([6., 6., 6., 6.], dtype=float32)>

In [ ]:
c[-1].assign( 1 )

AttributeError: ignored

# Create tensors

In [ ]:
tf.constant( np.zeros( (3,3, 3) ) )

<tf.Tensor: shape=(3, 3, 3), dtype=float64, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])>

In [ ]:
T1 = tf.ones( shape=(4,5) )

In [ ]:
tf.linspace(0,10, 11)

<tf.Tensor: shape=(11,), dtype=float64, numpy=array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])>

In [ ]:
tf.range( 0,10, 2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 2, 4, 6, 8], dtype=int32)>

In [ ]:
tf.random.normal( shape=(3,3 ))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.3236749 ,  0.34724718, -0.20358713],
       [ 0.05412317, -0.9902977 ,  0.4186295 ],
       [ 0.00702682, -0.4520554 ,  1.201991  ]], dtype=float32)>

In [ ]:
tf.zeros_like( T1 ) 

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

# Tensor Atrributes and Methods 

In [ ]:
t = tf.ones( shape=(2,2,3) )

In [ ]:
dir( t )

In [ ]:
t.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [ ]:
t.dtype

tf.float32

In [ ]:
t.ndim

3

In [ ]:
t.shape

TensorShape([2, 2, 3])

In [ ]:
t.numpy()

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)

# Common Operations

In [ ]:
t = tf.ones( shape=(12,1))

In [ ]:
t

<tf.Tensor: shape=(12, 1), dtype=float32, numpy=
array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]], dtype=float32)>

In [ ]:
tf.reshape( t, shape=(3,2,2) )

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)>

In [ ]:
tf.one_hot( indices=[0,1], depth=2) # one-hot encoding

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.]], dtype=float32)>

Tensor Math

In [ ]:
A = tf.random.uniform( shape=(3,3), minval=0, maxval=10 )
print(A)

tf.Tensor(
[[0.63869596 1.3258636  1.7300296 ]
 [6.0885096  1.244396   9.320445  ]
 [8.372755   0.62639475 3.6030924 ]], shape=(3, 3), dtype=float32)


In [ ]:
B = tf.random.uniform( shape=(3,3), minval=0, maxval=10 )
print(B)

tf.Tensor(
[[8.043498   0.12004972 7.4548554 ]
 [7.217293   6.8369045  1.5355527 ]
 [2.8805506  4.040873   1.53229   ]], shape=(3, 3), dtype=float32)


In [ ]:
x = tf.random.uniform( shape=(3,1), minval=0, maxval=10 )
print(x)

tf.Tensor(
[[8.251499 ]
 [6.4755106]
 [1.094284 ]], shape=(3, 1), dtype=float32)


In [ ]:
A + B

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 8.682194 ,  1.4459133,  9.184885 ],
       [13.305802 ,  8.081301 , 10.855998 ],
       [11.253305 ,  4.667268 ,  5.1353827]], dtype=float32)>

In [ ]:
A * B

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 5.1373496 ,  0.15916955, 12.89712   ],
       [43.942554  ,  8.507816  , 14.312035  ],
       [24.118145  ,  2.5311816 ,  5.5209823 ]], dtype=float32)>

In [ ]:
A @ B

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[19.689934, 16.132309,  9.448226],
       [84.8021  , 46.901474, 61.581417],
       [82.246   , 19.847387, 68.90052 ]], dtype=float32)>

In [ ]:
tf.matmul(A, x)

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[15.748987],
       [68.49664 ],
       [77.08682 ]], dtype=float32)>

In [ ]:
x**2

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[68.08724  ],
       [41.932236 ],
       [ 1.1974576]], dtype=float32)>

In [ ]:
x

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[8.251499 ],
       [6.4755106],
       [1.094284 ]], dtype=float32)>

In [ ]:
tf.reduce_sum(x)

<tf.Tensor: shape=(), dtype=float32, numpy=15.821294>

In [ ]:
np.sum( )

# tf.Variable

In [ ]:
v1 = tf.Variable( tf.constant(2.0, shape=[4]) , dtype=tf.float32 )

In [ ]:
v1

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([2., 2., 2., 2.], dtype=float32)>

In [ ]:
v2 = tf.Variable( np.ones(shape=[4,3]), dtype='float32' )

In [ ]:
v2

<tf.Variable 'Variable:0' shape=(4, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
v3 = tf.Variable( tf.keras.initializers.RandomNormal( )( shape=[3,4] ) )

In [ ]:
v3

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[ 0.02142467, -0.04677688,  0.0814281 , -0.00221738],
       [ 0.04548194,  0.07921734,  0.01815587, -0.02030472],
       [-0.05589097, -0.04962171, -0.02225611, -0.02255425]],
      dtype=float32)>

In [ ]:
v = tf.Variable( np.zeros(shape=[4,3] ) )

In [ ]:
v

<tf.Variable 'Variable:0' shape=(4, 3) dtype=float64, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])>

In [ ]:
v[0,2].assign( 1.0 )

<tf.Variable 'UnreadVariable' shape=(4, 3) dtype=float64, numpy=
array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])>

In [ ]:
v

<tf.Variable 'Variable:0' shape=(4, 3) dtype=float64, numpy=
array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])>

In [ ]:
v[2:, :2].assign( [[3,3],[3,3]] )

<tf.Variable 'UnreadVariable' shape=(4, 3) dtype=float64, numpy=
array([[0., 0., 1.],
       [0., 0., 0.],
       [3., 3., 0.],
       [3., 3., 0.]])>

In [ ]:
v

<tf.Variable 'Variable:0' shape=(4, 3) dtype=float64, numpy=
array([[0., 0., 1.],
       [0., 0., 0.],
       [3., 3., 0.],
       [3., 3., 0.]])>