

---

# Numpy


Forma corta de *Numerical Python*, `numpy` es una librería que proporciona herramientas para trabajar con alto rendimiento sobre arreglos multidimensionales, la razón por la que es tan importante para Data Science con Python es que casi todas las bibliotecas en este campo confían en NumPy como uno de sus principales bloques de construcción.

Numpy también es increíblemente rápido, ya que tiene enlaces a bibliotecas C.



## Características
Dentro de las principales características de `numpy` se encuentran:
- Ofrece un poderoso objeto para manipular arreglos multidimensionales: `ndarray`.
- Posee herramientas para realizar operaciones matemáticas y lógicas sobre arreglos, operaciones relacionadas con algebra lineal, transformadas de Fourier, entre otras.

Para importar los módulos de la librería `numpy`, por convención se utiliza:

In [ ]:
import numpy as np   # 'np' alias de numpy



---
## Arrays


Las funcionalidades de `numpy` se basan en en el objeto `ndarray`.

Un `ndarray`, también conocido por el alias de `array`, es un arreglo N-dimensional con elementos del mismo tipo e indexado por una tupla de enteros positivos.


```python
a = numpy.array(data, dtype = None, ndmin = 0, ...)
```
- data: datos de mismo tipo en forma de matriz o una secuencia anidada.
- dtype (opcional): tipos de datos deseados en el arreglo. 
- ndmin: especifica el número mínimo de dimensiones del arreglo resultante.



## Creación de Arrays

La forma mas facil de crear un arreglo es utilizando el objeto `ndarray`.

In [ ]:
array_1d = np.array([1,2,3,4,5])
array_1d

array([1, 2, 3, 4, 5])

In [ ]:
array_2d = np.array([[0,1,2,3],[4,6,8,10],[1,3,5,7]])  
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [ 1,  3,  5,  7]])

In [ ]:
array_3d = np.array([[[1,2,3],[11,22,33],[111,222,333]],[[4,5,6],[44,55,66],[444,555,666]]])  
array_3d

array([[[  1,   2,   3],
        [ 11,  22,  33],
        [111, 222, 333]],

       [[  4,   5,   6],
        [ 44,  55,  66],
        [444, 555, 666]]])

**Desde una lista de Python**

Podemos crear una matriz mediante la conversión directa de una lista o lista de listas:

In [ ]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [ ]:
my_array = np.array(my_list)
my_array

array([1, 2, 3])

In [ ]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np_matrix = np.array(my_matrix)
np_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Diferencias:**

In [ ]:
my_list+my_list

[1, 2, 3, 1, 2, 3]

In [ ]:
my_array+my_array

array([2, 4, 6])

In [ ]:
help(my_list)

Help on list object:

class list(object)
 |  list() -> new empty list
 |  list(iterable) -> new list initialized from iterable's items
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |  
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  __iter__(self, /)
 |      Implement iter(self).
 |  
 |  __le__(self, value, /

In [ ]:
help(my_array)

Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any objec

## Examinando sus atributos



Dentro de los principales atributos del objeto `ndarray`, se encuentran:
- `ndarray.shape`: tupla con las dimensiones del arreglo. 
- `ndarray.ndim`: numero de dimensiones del arreglo.
- `ndarray.size`: número de elementos del arreglo.
- `ndarray.dtype`: tipo de dato de los elementos del arreglo. 

In [ ]:
a = np.array(my_matrix)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a.shape

(3, 3)

In [ ]:
test = np.array(my_list)
test.shape

(3,)

In [ ]:
a.ndim

2

In [ ]:
a.size

9

In [ ]:
a.dtype

dtype('int64')

**Creacion de Arrays pre-definidos**



Numpy cuenta con funciones especiales para crear arreglos con valores definidos por defecto, por ejemplo:
- **zeros**: crea arreglo solamente con 0's.
- **ones**: crea arreglo solamente con 1's.
- **eye**: crea una matriz identidad de tamaño n.
- **empty**: crea un arreglo sin inicializar de forma y dtype especificados.
- **full**: crea un arreglo con un valor constante especificado.

In [ ]:
# Matrix de 0's
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# Matrix de 1's
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
# Matrix identidad
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.empty((2,3), dtype=int)

array([[56834960,        0,        0],
       [       0,        0,        0]])

**arange**

Devuelve valores espaciados uniformemente dentro de un intervalo dado.

In [ ]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,10,2.5)

array([0. , 2.5, 5. , 7.5])



## Aritmética con Arrays

El objeto `ndarray` es importante porque permite realizar cualquier operación entre arreglos sin escribir ningún bucle *for*.

Cualquier operación aritmética con arreglos del mismo tamaño aplica una operación elemento a elemento:

In [ ]:
a = np.array([[1,2,3],
              [4,5,6]])  

b = np.array([[2,4,6],
              [1,3,5]])  

c = np.array([[1,2],
              [3,4],
              [5,6]])

In [ ]:
a.shape

(2, 3)

In [ ]:
c.shape

(3, 2)

In [ ]:
a + b

array([[ 3,  6,  9],
       [ 5,  8, 11]])

In [ ]:
a - b

array([[-1, -2, -3],
       [ 3,  2,  1]])



Las operaciones aritméticas con escalares se aplica a cada elemento del arreglo.

In [ ]:
2*a

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [ ]:
1+a

array([[2, 3, 4],
       [5, 6, 7]])

In [ ]:
a * b

array([[ 2,  8, 18],
       [ 4, 15, 30]])

In [ ]:
np.multiply(a,b) # equivalente a: a * b

array([[ 2,  8, 18],
       [ 4, 15, 30]])

In [ ]:
# Producto Matricial
np.dot(a,b)

ValueError: ignored

In [ ]:
# Producto Matricial
np.dot(a,c)

array([[22, 28],
       [49, 64]])

In [ ]:
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
c.transpose()

array([[1, 3, 5],
       [2, 4, 6]])



##  Indexing y slicing en Arrays

Tecnicas muy similares de *indexing* y *slicing* para acceder a las *listas de Python* son también utilizadas en los *Arrays de Numpy*. Sin embargo, una de las principales diferencias es que los subconjuntos son vistas, es decir, cualquier cambio modifica directamente al array original.


In [ ]:
a = np.arange(1,21,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
a[2:5]

array([5, 7, 9])

In [ ]:
a[:5]

array([1, 3, 5, 7, 9])

In [ ]:
a[5:]

array([11, 13, 15, 17, 19])

In [ ]:
a[[4,6,8]]

array([ 9, 13, 17])

In [ ]:
a[ [1,-2] ]

array([ 3, 17])

In [ ]:
print(a)

[ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
# Modificar un array
a[3:6] = 10
a

array([ 1,  3,  5, 10, 10, 10, 13, 15, 17, 19])

In [ ]:
# El seleccionar una parte del array original, estás apuntando hacia ese subarrays del array original
b = a[3:6]
print("Al inicio:",b)

b[:] = 5
print("Al final:",b)

Al inicio: [10 10 10]
Al final: [5 5 5]


In [ ]:
# Ahora, revisemos los valores de "a"
a

array([ 1,  3,  5,  5,  5,  5, 13, 15, 17, 19])



Si se quiere copiar una parte de un arreglo en lugar de una vista, es necesario copiar explícitamente el arreglo.

In [ ]:
b = a[3:6].copy()

In [ ]:
b

array([5, 5, 5])

In [ ]:
b[:] = 1
b

array([1, 1, 1])

In [ ]:
a

array([ 1,  3,  5,  5,  5,  5, 13, 15, 17, 19])



El principo es el mismo para arreglos multidimensionales.

In [ ]:
a = np.array([[ 0,  1,  2,  3],
              [ 4,  6,  8, 10],
              [ 1,  3,  5,  7]])
a

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [ 1,  3,  5,  7]])

In [ ]:
a[0:2,:3]

array([[0, 1, 2],
       [4, 6, 8]])

In [ ]:
# Modificar una matrix
a[0:2,:3] = -1
a

array([[-1, -1, -1,  3],
       [-1, -1, -1, 10],
       [ 1,  3,  5,  7]])

In [ ]:
a[-2:-1 , ]

array([[ 4,  6,  8, 10]])



## Funciones universales

Las funciones universales son funciones que ejecutan operaciones element-wise sobre los datos en los arreglos.

Generalmente, este tipo de funciones se aplican a cada elemento de un arreglo, por ejemplo:

In [ ]:
a = [4,9,16,25]

In [ ]:
b = np.sqrt(a)
b

In [ ]:
np.exp(a)

In [ ]:
np.log(a)



Por otro lado, hay funciones universales que realizan operaciones con 2 arrays y regresan un array como salida.

In [ ]:
np.add(a,a)

In [ ]:
np.multiply(a,a)

In [ ]:
np.power(a,3)



## Filtros en Arrays

Suponga que desea tomar el valor de una matriz `X` cuando el valor correspondiente en una condición es True, y de lo contrario tome el valor de la matriz `Y`. Dentro de *Numpy* hay una función llamada **np.where** que resuelve la situación anterior.

```python
result = np.where(cond, xarr, yarr)
```

In [ ]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([20.1, 20.2, 20.3, 20.4, 20.5])
cond = np.array([True, False, True, True, False])

In [ ]:
print('xarr:', xarr)
print('yarr:', yarr)
print('cond:', cond)

In [ ]:
np.where(cond,xarr,yarr)

In [ ]:
np.where(xarr>1.3, 1, 0)

In [ ]:
np.where(xarr>1.3, 'mayor', 'menor')



## Métodos matemáticos y estadísticos

Un conjunto de funciones matemáticas que computan estadísticas sobre una matriz completa o sobre los datos a lo largo de un eje son accesibles como métodos de la clase `ndarray`. Las funciones como suma, media y desviación estándar se pueden usar llamando al método de instancia de matriz o usando la función * numpy * de nivel superior.

In [ ]:
a = np.arange(12).reshape(4,3)
a

In [ ]:
a.mean()

In [ ]:
np.mean(a)



La operación anterior se ha realizado en toda la matriz, pero es posible especificar el eje, como se muestra a continuación:

In [ ]:
a.shape

In [ ]:
# axis=0 : indica operar sobre el primer eje
a.sum(axis=0)

In [ ]:
# axis=1 : indica operar sobre el segundo eje
a.sum(axis=1)

In [ ]:
a.min(axis=0)

In [ ]:
a.max(axis=1)

In [ ]:
a.mean() # promedio

In [ ]:
np.median(a) # mediana

In [ ]:
a.std(0) # Desviacion Estandar

In [ ]:
# Percentiles

In [ ]:
my_array = np.arange(0,100,4)
my_array

In [ ]:
np.percentile(a=my_array, q=[25,50,75],)