In [1]:
import numpy as np
from scipy import linalg

En una feria se cobra 8 dolares a los alumnos y 4 doalres a los niños.
Si el sabado hubo 1000 asistentes ganando 6400 y el domingo hubo 800 asisntentes ganando 4800

¿Cuantos adultos y niños llegaron durante el fin de semana?

In [2]:
pc = np.matrix([
    [8, 4],  
    [1, 1]
])

h = np.matrix([
    [6400],
    [1000]
])
linalg.inv(pc)*h

matrix([[600.],
        [400.]])

In [3]:
pc = np.matrix([
    [8, 4],  
    [1, 1]
])

h = np.matrix([
    [4800],
    [800]
])
linalg.inv(pc)*h

matrix([[400.],
        [400.]])

In [4]:
print('adultos: ', 600 + 400)
print('niños: ', 400 + 400)

adultos:  1000
niños:  800


In [5]:
mensaje = [72, 39, 35, 245, 127, 82, 68, 36, 22, 188, 108, 102, 136, 70, 36]

codificadora = np.matrix([
    [3, 6, 2],  
    [2, 3, 1],
    [3, 1, 1]
])

In [7]:
def decodificar(mensaje, matriz):
    inversa = linalg.inv(matriz)
    
    n_filas = inversa.shape[0]
    
    formateo = np.matrix(
        np.array(mensaje).reshape(5, 3)
    ).T
    
    
    
    print(inversa.shape[0])
    print(formateo)
    print(type(formateo))
    print(inversa*formateo)

decodificar(mensaje, codificadora)

3
[[ 72 245  68 188 136]
 [ 39 127  36 108  70]
 [ 35  82  22 102  36]]
<class 'numpy.matrix'>
[[ 6.  9.  4. 28.  4.]
 [ 5. 27.  9. 17. 19.]
 [12. 28.  1.  1.  5.]]
